### PR TITLE
Update submodule inside build.rs

### PR DESCRIPTION
**Pull request by Keats**

### CODE REVIEW

**Comment by remexre** [comment]
Sorry for disappearing, was out of town. This doesn't seem to be a fix for me:

```
$ git clone git@github.com:compass-rs/sass-rs.git
...
$ cd sass-rs
$ git checkout vp_build_git
Branch 'vp_build_git' set up to track remote branch 'vp_build_git' from 'origin'.
Switched to a new branch 'vp_build_git'
$ cargo build
    Updating crates.io index
   Compiling libc v0.2.66
   Compiling pkg-config v0.3.17
   Compiling num_cpus v1.11.1
   Compiling sass-sys v0.4.15 (/tmp/sass-rs/sass-sys)
   Compiling sass-rs v0.2.2 (/tmp/sass-rs)
warning: unnecessary trailing semicolon
  --> src/bindings/context.rs:41:87
   |
41 |     fn make_sass_context(c_sass_context: *mut sass_sys::Sass_Context) -> SassContext {;
   |                                                                                       ^ help: remove this semicolon
   |
   = note: `#[warn(redundant_semicolon)]` on by default

error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/nathan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.1dkd3motnfp1i0u2.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.1f0qt5x1o7wyt8.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.1kdlpmu3o2bi95lk.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.1oauvrjzotxvijy9.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.1smx47440fryrgtm.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.22dhuygc5r7ygb3n.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.22yqqrvva2hiud5v.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.22zkz0yjvvp0vw7k.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.264klm5aphp24oek.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.2c240nt01aamnkfe.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.2h3gsh0lyn7d3rvi.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.2pujstbao6w1gdcx.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.2qrvuvgn28muv0r0.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.2uy3m7te8jqcrbf3.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.2wlj7ki0vwuy5q94.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.304x8wqxst4t4slo.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.39pbl87c6xmgwpvp.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.3btig83yoscpkava.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.3headdt03tuqvuer.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.3mox1w9blh2nmmdr.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.3z1moj0uc5domoba.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.4agtah1yxh4qz4sq.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.4b53xavaysv38v20.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.4cc70nnmilcdcre2.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.4n888rroweoldx9b.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.4o0ujp9p60taya3z.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.4q5rfc9ckswscxm7.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.52lrr3e6esgvshjj.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.53bv1jvz4owp1s15.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.54z3wkptu6jvj6ti.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.57x222aa5pkusuny.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.5eiqh25hrdcruw2j.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.6fp70fd7itix2er.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.6smi99lbts21ksn.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.7ybloi76kgzsi3w.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.bd5x7mysj33i2yf.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.jpkceqetnfs6t1r.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.nud2m3i87hlwq47.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.t3f7n1vr8ym5y46.rcgu.o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.xxhnhhd4lrns8tz.rcgu.o" "-o" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a" "/tmp/sass-rs/target/debug/deps/sass_rs-549ff39f834bda0a.16x64ybmste87lnz.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/tmp/sass-rs/target/debug/deps" "-L" "/tmp/sass-rs/target/debug/build/sass-sys-f372d4ad38810fbe/out/build/lib" "-L" "/home/nathan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/sass-rs/target/debug/deps/libsass_rs-fb8cc3a7e0c8588f.rlib" "/tmp/sass-rs/target/debug/deps/liblibc-52f675a24655d4b8.rlib" "/tmp/sass-rs/target/debug/deps/libsass_sys-4b03c3b52b4d54e1.rlib" "-Wl,--start-group" "/home/nathan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-74488c47a41eb313.rlib" "/home/nathan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-efbc2c947951b8cc.rlib" "/home/nathan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-b177382d9a04ffbe.rlib" "/home/nathan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-ba7d2244d33447d5.rlib" "/home/nathan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace-39569dc87e4ea301.rlib" "/home/nathan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-cd9e255bd82ddb5c.rlib" "/home/nathan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-f83165e777dccb8d.rlib" "/home/nathan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-10b085de263b1750.rlib" "/home/nathan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-9a4a22edf44da957.rlib" "/home/nathan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-68fabc677efa98de.rlib" "/home/nathan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-026dc0061b48e8b6.rlib" "/home/nathan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-7bf75bb619341145.rlib" "/home/nathan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-ef54709e300503ed.rlib" "-Wl,--end-group" "/home/nathan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-4ed27d8420cb4abc.rlib" "-Wl,-Bdynamic" "-lutil" "-lutil" "-lc++_shared" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil"
  = note: /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /tmp/sass-rs/target/debug/deps/libsass_sys-4b03c3b52b4d54e1.rlib(sass_context.o): undefined reference to symbol '__cxa_guard_release'
          /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../lib64/../lib64/libc++abi.so.1: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status


error: aborting due to previous error

error: could not compile `sass-rs`.

To learn more, run the command again with --verbose.
```

**Comment by Keats** [comment]
@remexre Can you try fiddling with the build.rs to see what makes it build?

**Comment by cup** [comment]
https://github.com/compass-rs/sass-rs/issues/63

**Comment by Keats** [comment]
@remexre I'll merge and release that in the meantime, we can continue discussing here.

**Pull request merged**
