### PR TITLE
Update libsass

### PR DESCRIPTION
**Pull request by Keats**

### CODE REVIEW

**Comment by Keats** [comment]
@killercup would that work?

**Comment by killercup** [comment]
Yeah, I'd assume so. You can test this by running `cargo package` and see what's in the file (.crate is just .tar.gz iirc).

**Comment by Keats** [comment]
Turns out there is a copy of the package version in target/package automatically, no need to unzip anything

**Comment by Keats** [comment]
0.4.15 is published and will be part of zola 0.10
I'm not going to release 0.9.1 since hopefully 0.10 is going to happen soon and there are already breaking changes in the codebase.

**Pull request merged**
